### ISSUE TITLE
What is Coffee Code?

### ISSUE THREAD

**Issue by joed7** [HackCU/ama#1]
I see a lot of posts on HackCU slack regarding Coffee Code. I was just curious what is it about?

**Comment by dawsonbotsford** [comment]
Hi Joe, thanks for asking!

CoffeeCode is our initiative to get people coding for the sake of coding! Every Monday we meet at a coffee shop and code for 2+ hours together. It can be side projects of any kind.

Join us next week! You can read the manifesto here: https://medium.com/@dbsweets/coffeecode-mondays-90d8e273e8c6
