### ISSUE TITLE
When will application decisions be announced?

### ISSUE THREAD

**Issue by fwoelm** [HackCU/ama#2]
With Hack CU coming up in three weeks (psyched!), I'm wondering when we can expect to hear about our application decisions. Keep on hacking!

**Comment by dawsonbotsford** [comment]
Hey @fwoelm, thanks for the ama!

Our next round of acceptances will be out on this Friday (March 18th). Keep in mind we already did round one releases, so ensure if you did the application a month or more ago that you didn't miss the acceptance email.

Looking forward to having you!  
Cheers :beers:
