### ISSUE TITLE
Will there be a Writeathon again?

### ISSUE THREAD

**Issue by dawsonbotsford** [HackCU/ama#3]
In 2016, HackCU hosted a writeathon in order to clearly show encouragement of other types of building. It was successful, albeit small. 

1. What is the culture of HackCU now as it pertains to supporting other types of builders beyond computer science students?

2. Will there be another writeathon or similar sub-event within HackCU?

Thanks!

**Comment by alexwalling** [comment]
1) We're really hoping to continue building HackCU beyond just computer science students through marketing, workshops, and different sub-events! We're hoping to do a design workshop next semester and would love to get both design/art students and computer science students involved in that workshop. We will also be having more hardware than just what MLH is able to provide us for the hardware hackers in our community.

2) We're still working on planning HackCU III and thus don't have any specific plans! Now that Local Hack Day is finished we will be able to solidify plans for what we want to do at HackCU III!
